# Generated by Django 4.1.1 on 2022-10-18 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_datetime', models.CharField(default='2022-10-18 12:50:59', max_length=20, verbose_name='Дата отправки')),
                ('channel_id', models.IntegerField(default=-1001516084523, verbose_name='ID канала')),
                ('url', models.CharField(default='https://sweetspeak.ru/', max_length=256, verbose_name='URL статьи')),
                ('post', models.TextField(default='Этот пост еще не написан', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Расписание постов',
                'verbose_name_plural': 'Расписание постов',
            },
        ),
        migrations.CreateModel(
            name='PublishedPosts',
            fields=[
                ('scheduledposts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.scheduledposts')),
            ],
            options={
                'verbose_name': 'Опубликованные посты',
                'verbose_name_plural': 'Опубликованные посты',
            },
            bases=('bot.scheduledposts',),
        ),
    ]
