# Generated by Django 4.1.1 on 2022-10-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_datetime', models.CharField(default='2022-10-08 23:00:00', max_length=8, verbose_name='Дата отправки')),
                ('channel_id', models.IntegerField(default=-1001516084523, verbose_name='ID канала')),
                ('url', models.CharField(default='https://sweetspeak.ru/kak-privlech-k-sebe-vnimanie-v-prilozhenii-znakomstv/', max_length=256, verbose_name='URL статьи')),
                ('post', models.TextField(default='С одной стороны, с появлением Интернета и онлайн-сервисов для общения                   знакомиться с новыми людьми стало легче. Общаться можно в любое время,                   с любых устройств и в любых условиях, при этом неважно, как именно ты                   выглядишь и как быстро ориентируешься в разговоре – переписка дает                   достаточно времени для того, чтобы обдумать любой свой ответ.                   Но теперь многие парни и девушки столкнулись с другой проблемой: они                   не знают, как начать общение на сайте знакомств и заинтересовать                   собеседника. И при всей упрощенности беседы в Сети вдруг оказалось,                   что привлечь потенциального романтического партнера онлайн не так-то и просто.\n                  https://sweetspeak.ru/kak-privlech-k-sebe-vnimanie-v-prilozhenii-znakomstv/\n                  ', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Расписание постов',
                'verbose_name_plural': 'Расписание постов',
            },
        ),
    ]
