# Generated by Django 4.1.2 on 2022-10-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_datetime', models.CharField(default='2022-10-25 12:23:44', max_length=20, verbose_name='Дата отправки')),
                ('channel_id', models.IntegerField(default=-1001516084523, verbose_name='ID канала')),
                ('url', models.CharField(default='https://sweetspeak.ru/', max_length=256, verbose_name='URL статьи')),
                ('post', models.TextField(default='Этот пост еще не написан', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Расписание постов',
                'verbose_name_plural': 'Расписание постов',
            },
        ),
    ]
