# Generated by Django 4.1.2 on 2022-10-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_datetime_p', models.CharField(default='2022-10-25 12:31:29', max_length=20, verbose_name='Дата отправки')),
                ('channel_id_p', models.IntegerField(default=-1001516084523, verbose_name='ID канала')),
                ('url_p', models.CharField(default='https://sweetspeak.ru/', max_length=256, verbose_name='URL статьи')),
                ('post_p', models.TextField(default='Этот пост еще не написан', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Опубликованные посты',
                'verbose_name_plural': 'Опубликованные посты',
            },
        ),
        migrations.AlterField(
            model_name='scheduledposts',
            name='sending_datetime',
            field=models.CharField(default='2022-10-25 12:31:29', max_length=20, verbose_name='Дата отправки'),
        ),
    ]
